### ISSUE TITLE
GitLab access with YNH right 

### ISSUE THREAD

**Issue by JRelland** [YunoHost-Apps/gitlab_ynh#102]
Hi thank you for GitLab on YNH.
I installed it and it works perfectly.
I recommend it :)

It's just about YNH's user access for an "internal projet"
I was thinking that, with a YNH account, when you click on the GiLab icon, 
you go straightly to GitLab

In fact, you are front of a sign in/sign up panel.

Is it possible to access to GitLab without signing for YNH's users?

(Until now, I use it thought the admin account :) )

Thank you again, José from France.

**Comment by kay0u** [comment]
Hi!
Thank you, don't hesitate if you encounter any issue with this app :-)

We can't use an "auto-login" for YunoHost users because Gitlab doesn't support (Yet?) `HTTP Basic Auth` (system used with Nextcloud for example).

You still can access to your public repos without login by clicking on the `explore` button at the bottom of the login page.

**Comment by JRelland** [comment]
Hi @kay0u Thank you for this fast reply.

OK I understand. Yes, NextCloud makes us more "demanding" :)

Ok for the Explore link (quite small :) ) but it works and I'll mention it in our documentation.

At the end, no problem as the "YNH" account has been created and we can sign in (without sign up in GitHub)

Have a good time. José, confined, from France :)

**Comment by JRelland** [comment]
I closed it

**Comment by kay0u** [comment]
In the admin area -> Settings -> General -> Sign-in restrictions -> Home page URL -> Put https://gitlabdomain/gitlabpath/explore (with **/explore** at the end)

Have a good time. Kay0u, confined in France too ;-)
